### ISSUE TITLE
matter::sparse_mat path

### ISSUE THREAD

**Issue by MatthewOGoodman** [kuwisdelu/matter#17]
I am probably missing something, but I could not find a way to add the path to the constructor for matter::sparse_mat. Can you let me know how this is done?

And, thanks so much for the great work on this package!

**Comment by kuwisdelu** [comment]
For `sparse_mat`, the paths are not provided directly to the constructor, because it can be either in-memory of out-of-memory. If using out-of-memory data in a sparse matrix, you would first construct either `matter_vec` (if passing a `pointers` array) or `matter_list` (if not passing a `pointers` array) and then pass these as the `index` and `data` arguments to `sparse_mat()`.
